In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
plt.rc('font', family='Malgun Gothic') # 한글
import warnings
warnings.filterwarnings('ignore')

In [70]:
train = pd.read_csv('train.csv')
# train = train.iloc[:132]
train.tail()

,단지명,전용면적,일일가격,위도,경도,지하철거리,환율,가장 가까운 버스정류장까지 거리(m),가장 가까운 버스정류장,1000m맛집,...,지하철역_시청역,지하철역_신금호역,지하철역_신당역,지하철역_신설동역,지하철역_약수역,지하철역_을지로4가역,지하철역_청구역,지하철역_충무로역,지하철역_충정로(경기대입구)역,지하철역_회현(남대문시장)역
1221,청구e편한세상,84.95,43.750000,37.559960,127.015451,148.070576,1224.2,70.234841,청구역,63,...,0,0,0,0,0,0,1,0,0,0
1222,남산타운,59.94,17.625000,37.547167,127.005677,153.773224,1408.0,38.785797,버티고개,30,...,0,0,0,0,0,0,0,0,0,0
1223,약수하이츠,65.37,20.729167,37.555192,127.016359,358.131262,1394.2,392.934357,신당동대우푸르지오.금호여중,47,...,0,1,0,0,0,0,0,0,0,0
1224,남산타운,84.88,32.916667,37.547167,127.005677,153.773224,1374.8,38.785797,버티고개,30,...,0,0,0,0,0,0,0,0,0,0
1225,동대문와이즈캐슬,15.55,9.291667,37.565754,127.015444,76.313787,1234.9,102.600962,충무아트센터.스포츠센터.중부소방서,52,...,0,0,1,0,0,0,0,0,0,0

In [71]:
train = train.loc[train['전용면적'] <= 100,:]

In [72]:
train

,단지명,전용면적,일일가격,위도,경도,지하철거리,환율,가장 가까운 버스정류장까지 거리(m),가장 가까운 버스정류장,1000m맛집,...,지하철역_시청역,지하철역_신금호역,지하철역_신당역,지하철역_신설동역,지하철역_약수역,지하철역_을지로4가역,지하철역_청구역,지하철역_충무로역,지하철역_충정로(경기대입구)역,지하철역_회현(남대문시장)역
0,WECOSTAY Myeongdong B,26.00,9.375000,37.563297,126.998434,370.075977,1304.4,127.677199,퇴계로5가,60,...,0,0,0,0,0,1,0,0,0,0
1,urbanstay : 명동역 5분거리 / 힙지로 #취사가능,26.00,12.126000,37.563184,126.993240,208.089513,1304.4,21.254979,초동,80,...,0,0,0,0,0,0,0,1,0,0
2,"[쉼,]고층 편안한 숙소",26.00,9.543700,37.564704,126.993192,221.545884,1304.4,150.876995,초동,79,...,0,0,0,0,0,0,0,0,0,0
3,어반스테이 명동 님이 호스팅하는 레지던스 전체1,26.00,12.126000,37.564046,126.992536,261.581668,1304.4,92.860942,초동,80,...,0,0,0,0,0,0,0,0,0,0
4,어반스테이 명동 님이 호스팅하는 레지던스 전체2,26.00,12.126000,37.564326,126.992977,247.187075,1304.4,109.408482,초동,79,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,청구e편한세상,84.95,43.750000,37.559960,127.015451,148.070576,1224.2,70.234841,청구역,63,...,0,0,0,0,0,0,1,0,0,0
1222,남산타운,59.94,17.625000,37.547167,127.005677,153.773224,1408.0,38.785797,버티고개,30,...,0,0,0,0,0,0,0,0,0,0
1223,약수하이츠,65.37,20.729167,37.555192,127.016359,358.131262,1394.2,392.934357,신당동대우푸르지오.금호여중,47,...,0,1,0,0,0,0,0,0,0,0
1224,남산타운,84.88,32.916667,37.547167,127.005677,153.773224,1374.8,38.785797,버티고개,30,...,0,0,0,0,0,0,0,0,0,0
1225,동대문와이즈캐슬,15.55,9.291667,37.565754,127.015444,76.313787,1234.9,102.600962,충무아트센터.스포츠센터.중부소방서,52,...,0,0,1,0,0,0,0,0,0,0

In [73]:
del_cols = ['단지명','가장 가까운 버스정류장','위도','경도']
train.drop(del_cols, axis =1 ,inplace=True)

target = '일일가격'

# x ,y split 
x = train.drop('일일가격', axis=1)
y = train['일일가격']

# 정규화
x =  (x-x.min())/(x.max() - x.min())

# train validation split
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.3, random_state =42)

In [74]:
x_train.isna().sum()

전용면적                    0
지하철거리                   0
환율                      0
가장 가까운 버스정류장까지 거리(m)    0
1000m맛집                 0
1000m문화공간               0
1000m문화재                0
1000m쇼핑                 0
소비자물가지수                 0
종합주가지수                  0
주택담보대출금리                0
지하철역_을지로3가역             0
지하철역_동대문역사문화공원역         0
지하철역_동대입구역              0
지하철역_동묘앞역               0
지하철역_명동역                0
지하철역_버티고개역              0
지하철역_상왕십리역              0
지하철역_서대문역               0
지하철역_서울역                0
지하철역_시청역                0
지하철역_신금호역               0
지하철역_신당역                0
지하철역_신설동역               0
지하철역_약수역                0
지하철역_을지로4가역             0
지하철역_청구역                0
지하철역_충무로역               0
지하철역_충정로(경기대입구)역        0
지하철역_회현(남대문시장)역         0
dtype: int64

In [75]:
x_val.isna().sum()

전용면적                    0
지하철거리                   0
환율                      0
가장 가까운 버스정류장까지 거리(m)    0
1000m맛집                 0
1000m문화공간               0
1000m문화재                0
1000m쇼핑                 0
소비자물가지수                 0
종합주가지수                  0
주택담보대출금리                0
지하철역_을지로3가역             0
지하철역_동대문역사문화공원역         0
지하철역_동대입구역              0
지하철역_동묘앞역               0
지하철역_명동역                0
지하철역_버티고개역              0
지하철역_상왕십리역              0
지하철역_서대문역               0
지하철역_서울역                0
지하철역_시청역                0
지하철역_신금호역               0
지하철역_신당역                0
지하철역_신설동역               0
지하철역_약수역                0
지하철역_을지로4가역             0
지하철역_청구역                0
지하철역_충무로역               0
지하철역_충정로(경기대입구)역        0
지하철역_회현(남대문시장)역         0
dtype: int64

In [76]:
print(len(x_train))
print(len(x_val))
print(len(y_train))
print(len(y_val))

756
324
756
324

In [77]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import *
from sklearn.model_selection import GridSearchCV,cross_val_score

model_rf = RandomForestRegressor(random_state =2022)

cv_score = cross_val_score(model_rf, x_train, y_train, cv=5)

print(cv_score)
print('평균 : ', cv_score.mean())

[0.71201764 0.67416653 0.69157075 0.6702642  0.66844679]
평균 :  0.6832931829575009

In [81]:
from xgboost import XGBRegressor, XGBRFRegressor
model_xgb = XGBRegressor()
model_xgb.fit(x_train, y_train)

y_pred = model_xgb.predict(x_val)

abs(y_pred - y_val).mean()

4.646074625474307

In [55]:
# 파라미터 선언
params = {'max_depth' : range(5,31)}

model = GridSearchCV(model_rf,
                   params,
                   cv=10,
                   scoring = 'r2')

model.fit(x_train, y_train)

print(model.cv_results_['mean_test_score'])

[0.73166209 0.74638618 0.75427299 0.75751146 0.76084788 0.7612979
 0.76374835 0.7656971  0.76055496 0.76095645 0.76016635 0.76357749
 0.76360714 0.76198697 0.76397867 0.76314224 0.76193481 0.7626658
 0.76122244 0.76256904 0.7621572  0.76234442 0.762028   0.76249908
 0.76232342 0.76234085]

In [59]:
# Ridge Regression
import numpy as np
from sklearn.linear_model import Ridge

# training the model
# alpha 값에 변화를 주며 튜닝 0.05, 0.5, 5, 10
tune = [0.001, 0.01,0.05, 0.5, 5, 10]
mae_list = []
for num in tune:
    ridgeReg = Ridge(alpha = num, normalize =True)
    ridgeReg.fit(x_train, y_train)
    pred = ridgeReg.predict(x_val)
    
    # Calculating MAE
    mae = np.mean(abs(pred  - y_val))
    mae_list.append(round(mae,2))
print('alpha = ',tune)
print('mae = ', mae_list)

alpha =  [0.001, 0.01, 0.05, 0.5, 5, 10]
mae =  [7.52, 7.55, 7.63, 8.27, 11.24, 11.94]

In [61]:
from sklearn.linear_model import Lasso

# training the model
# alpha 값에 변화를 주며 튜닝 0.05, 0.5, 5, 10
tune = [0.001, 0.01,0.05, 0.5, 5, 10]
mae_list = []
for num in tune:
    lassoReg = Lasso(alpha = num, normalize =True)
    lassoReg.fit(x_train, y_train)
    pred = lassoReg.predict(x_val)
    
    # Calculating MAE
    mae = np.mean(abs(pred  - y_val))
    mae_list.append(round(mae,2))
print(tune)
print(mae_list)

[0.001, 0.01, 0.05, 0.5, 5, 10]
[7.56, 7.72, 7.97, 12.94, 12.94, 12.94]

In [62]:
from sklearn.linear_model import ElasticNet

tune = [0.001, 0.01, 0.05, 0.1, 0.3, 0.5, 0.9]
mae_list = []

for num in tune:
    ENreg = ElasticNet(alpha =1, l1_ratio =num, normalize = False)
    ENreg.fit(x_train, y_train)
    pred = ENreg.predict(x_val)
    
    # Calculating MAE
    mae = np.mean(abs(pred  - y_val))
    mae_list.append(round(mae,2))

print(tune)
print(mae_list)

[0.001, 0.01, 0.05, 0.1, 0.3, 0.5, 0.9]
[12.51, 12.51, 12.51, 12.52, 12.52, 12.45, 11.48]

In [9]:
test = pd.read_csv('test.csv')
test

,단지명,전용면적,위도,경도,지하철거리,환율,1000m맛집,1000m문화공간,1000m문화재,1000m쇼핑,...,지하철역_신설동역,지하철역_약수역,지하철역_을지로4가역,지하철역_청구역,지하철역_충무로역,지하철역_충정로(경기대입구)역,지하철역_회현(남대문시장)역,소비자물가지수,종합주가지수,주택담보대출금리
0,한진해모로,27.2700,37.563728,127.025711,329.285132,1185.5,18,7,4,16,...,0,0,0,0,0,0,0,104.69,2865.55,2.82
1,삼성사이버빌리지,59.7000,37.558927,126.964321,86.422853,1199.6,73,29,74,4,...,0,0,0,0,0,1,0,104.69,2865.55,2.82
2,서울역한라비발디센트럴,71.9832,37.554574,126.965847,376.530346,1199.6,67,24,65,4,...,0,0,0,0,0,0,0,104.69,2865.55,2.82
3,약수하이츠,84.8800,37.555192,127.016359,358.131262,1199.6,47,17,24,13,...,0,0,0,0,0,0,0,104.69,2865.55,2.82
4,리하우스(LEEHAUS),43.0560,37.559914,126.966633,200.555682,1202.4,102,32,89,7,...,0,0,0,0,0,1,0,104.69,2865.55,2.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,롯데캐슬,33.6200,37.570811,127.021464,533.615752,1325.6,21,7,4,23,...,1,0,0,0,0,0,0,109.10,2417.56,3.62
270,삼성홈타운,52.5900,37.562765,127.016877,381.618556,1338.4,50,16,26,30,...,0,0,0,0,0,0,0,109.10,2417.56,3.62
271,덕수궁롯데캐슬,56.2897,37.563708,126.970043,377.943375,1338.4,140,40,99,9,...,0,0,0,0,0,0,0,109.10,2417.56,3.62
272,남산타운,84.8800,37.547167,127.005677,153.773224,1340.0,30,13,28,6,...,0,0,0,0,0,0,0,109.10,2417.56,3.62
273,삼정아트테라스정동,18.0824,37.563251,126.972031,300.913761,1339.0,143,42,101,11,...,0,0,0,0,0,0,0,109.10,2417.56,3.62

In [ ]:
from sklearn.model_selection import train_test_split
target = 
x

x_train, y_train, x_test, y_test = train_test_split(x, test_size=0.2, random_state =42)